include:
  - compose-mysql.yaml
  - compose-traefik.yaml
  - compose-mkcert.yaml
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    depends_on:
      database:
        condition: service_healthy
#    deploy:
#      mode: replicated
#      replicas: 2
#      endpoint_mode: vip
#    restart: unless-stopped
    environment:
      SERVER_NAME: :8443
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php|php\.docker\.localhost$$}
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-userpassword}@database:3306/${MYSQL_DATABASE:-mydatabase}
      API_KEY_FILE: /run/secrets/api_key
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./certs/mysql_certs:/mysql_certs
      - ./certs/website_certs:/website_certs
    secrets:
      - api_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`php.docker.localhost`)"
      # Activation of TLS
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.services.php.loadbalancer.server.scheme=https"
      - "traefik.http.services.php.loadbalancer.server.port=8443"
volumes:
  caddy_data:
  caddy_config:

secrets:
  api_key:
    file: secrets/api_key.txt
