name: Docker Image CI

on:
    workflow_dispatch:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2

            - name: Lowercase repo owner
              id: prep
              run: |
                  repo_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
                  echo "repo_owner=${repo_owner}" >> $GITHUB_OUTPUT
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ steps.prep.outputs.repo_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  file: docker/Dockerfile
                  tags: ghcr.io/${{ steps.prep.outputs.repo_owner }}/api-platform:latest
                  cache-from: type=registry,ref=ghcr.io/${{ steps.prep.outputs.repo_owner }}/api-platform:buildcache
                  cache-to: type=registry,ref=ghcr.io/${{ steps.prep.outputs.repo_owner }}/api-platform:buildcache,mode=max
